name: Deploy Astro site to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  discussions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: bun install

      - name: Build with Astro
        run: |
          EXTRACTED_REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          
          PUBLIC_GITHUB_REPO_NAME="$EXTRACTED_REPO_NAME" bunx astro build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        env:
          SECRET_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLIC_GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          PUBLIC_GITHUB_REPO_ID: ${{ github.event.repository.node_id }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
